name = "polymathic"
description = "A portfolio theme for person of many talents"
license = "MIT"
homepage = "https://github.com/anvlkv/polymathic"
# The minimum version of Zola required
min_version = "0.17.2"
# An optional live demo URL
demo = "https://main--polymathic-demo.netlify.app/"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra.poly]
font_url = "https://fonts.googleapis.com/css2?family=AR+One+Sans:wght@400;700&display=swap"
favicon = false
manifest = false
logo = false
og_image= false
menu_order = false
social_outlink = false
license=false
fluid_page=true
breadcrumbs=true
animate_duration = "800ms"
animate_delay = "950ms"
animate_repeat = 1
taxonomy_preview_count = 3
taxonomy_config_path="taxonomies.yaml"

# The theme author info: you!
[author]
name = "Aleksandr Novolokov"
homepage = "https://a.nvlkv.xyz"
